language: python
python:
  - 3.6

os: linux
arch: 
  - amd64
  - arm64
  - arm64-graviton2
  
dist: bionic
group: edge
virt: vm
sudo: true
        
script:
  - virtualenv toilvenv
  - source toilvenv/bin/activate
  - make prepare
  - make develop
  - make test
